13 build reusable modal component
pobrok/frontend pull request #22
Opened 2022-09-30 07:48 UTC by mcekaj

2022-09-30 08:44 UTC, v-sekulic requested changes
MASJAAAAAAAA

2022-09-30 08:44 UTC, v-sekulic commented on src/common/components/AppModal/AppModal.module.scss
> +    border-radius: 0.5rem;
Mozda bi dobro bilo da extraktujemo ovaj border radius u neku scss varijablu jer vidim da ga koristimo na vise mjesta.
Mozes da koristis tailiwnd princip:
border-radius-sm
border-radius-md
border-radius-lg 
etc.

2022-09-30 08:44 UTC, v-sekulic commented on src/common/components/AppModal/AppModal.module.scss
> +    border-top-right-radius: 0.5rem;
I odje je ista vrijednost

2022-09-30 08:44 UTC, v-sekulic commented on src/common/components/AppModal/AppModal.module.scss
> +    align-items: center;
```
.all-center {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
Mozda da izdvojimo ovaj kod za centriranje u nesto poput ovoga i onda ga koristis preko `@extend`.
Recimo:
```
&---header{
    @extend all-center
}
```

2022-09-30 08:44 UTC, v-sekulic commented on src/common/components/AppModal/AppModal.module.scss
> +    padding: 1.25rem 0.625rem;
Probajmo da izdvojimo vrijednosti za spacing u posebne scss varijable po principu tejlvinda:
xs,sm,md,lg,xl,2xl etc

2022-09-30 08:44 UTC, v-sekulic commented on src/common/components/AppModal/AppModal.module.scss
> +  bottom: 0;
Valjalo bi izdvojiti ovaj dio koda u klasu npr: `.inset` i koristitit ga u kodu ovako:
```
.overlay {
   position: fixed;
   @extends .inset
}
```

2022-09-30 08:44 UTC, v-sekulic commented on src/common/components/AppModal/AppModal.module.scss
> +  bottom: 0;
Obratiti paznju kad se prave ove genericke klase da se izdvoje u neki fajl koji ce da se zove `_utility.scss` ili slicno jer nisu specificne za samo jednu komponentu vec mogu biti korisne svuda.
Takodje `.overlay` mi izgleda kao dobar kandidat za reusabilnost

2022-09-30 08:44 UTC, v-sekulic commented on src/common/components/AppModal/AppModal.tsx
> +          </button>
It would be good to extract this button into a component, could be useful for later. Name it something like `CloseButton`

2022-09-30 08:44 UTC, v-sekulic commented on src/styles/_variables.scss
> +$lightGray: #eeeeee;
This should go into a file named `_colors.scss`

2022-09-30 09:29 UTC, mcekaj commented on src/common/components/AppModal/AppModal.tsx
> +          </button>
In which cases you think this could be useful ?

2022-09-30 12:30 UTC, v-sekulic commented on src/common/components/AppModal/AppModal.tsx
> +          </button>
Anywhere where we need 'x' button, and since we don't have any official design, it might be useful

2022-10-04 08:32 UTC, v-sekulic approved these changes

2022-10-04 08:33 UTC, merged