react router with pages that we are using
pobrok/frontend pull request #23
Opened 2022-09-30 12:12 UTC by mcekaj

2022-09-30 14:24 UTC, v-sekulic commented on src/App.tsx
> +        <Route path="*" element={<NoMatchRoute />} />
Bilo bi dobro da se napravi konfiguracion objekat tipa:
```
const routes = [
   {
       path: '/',
       component: Home
   },
   {
       path: '/login,
       component: Login
   }
]
```

2022-09-30 14:25 UTC, v-sekulic commented on src/App.tsx
> +        <Route path="*" element={<NoMatchRoute />} />
I da se onda iterira u rutama

2022-09-30 14:25 UTC, v-sekulic requested changes
Komentari

2022-09-30 15:02 UTC, mcekaj commented on src/App.tsx
> +        <Route path="*" element={<NoMatchRoute />} />
changed

2022-10-05 09:34 UTC, v-sekulic requested changes
naming

2022-10-05 09:34 UTC, v-sekulic commented on src/common/components/Router/routes.ts
> +}
OBrati paznju na imenovanje ovdje. IRoutes je u mnozini iako on predstavlja interface za jedan objekat
Trebalo bi da ide `IRoute`
Pa ako ces da napravis niz da ide `IRoute[]`

2022-10-05 12:32 UTC, mcekaj commented on src/common/components/Router/routes.ts
> +}
promenjeno

2022-10-05 12:58 UTC, v-sekulic approved these changes

2022-10-05 12:58 UTC, merged